// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FinanceCalculator
{
	public partial class CurrencyChoice : UITableViewController
	{
		public CurrencyChoice (IntPtr handle) : base (handle)
		{
		}
	}
}
