// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FinanceCalculator
{
	public partial class IncomeTaxController : UIViewController
	{
		public IncomeTaxController (IntPtr handle) : base (handle)
		{
		}

		double expensesCalculated;

		public IncomeTaxController(double expensesRef) {
			expensesCalculated = expensesRef; 
		}
	}
}
