// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FinanceCalculator
{
	public partial class NavMasterController : UINavigationController
	{
		public NavMasterController (IntPtr handle) : base (handle)
		{
		}

		public NavMasterController(){}
	}
}
