// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using CoreGraphics;

namespace FinanceCalculator
{
	public partial class ScientificCalcController : UIViewController
	{
		public ScientificCalcController (IntPtr handle) : base (handle)
		{
		}
		UIButton number_0 = new UIButton(UIButtonType.System);

		UIButton number_1 = new UIButton(UIButtonType.System); 
		UIButton number_2 = new UIButton(UIButtonType.System);
		UIButton number_3 = new UIButton(UIButtonType.System);
		UIButton number_4 = new UIButton(UIButtonType.System);
		UIButton number_5 = new UIButton(UIButtonType.System);
		UIButton number_6 = new UIButton(UIButtonType.System);
		UIButton number_7 = new UIButton(UIButtonType.System);
		UIButton number_8 = new UIButton(UIButtonType.System);
		UIButton number_9 = new UIButton(UIButtonType.System);

		UILabel screen = new UILabel();

		UIButton Multiplying = new UIButton(UIButtonType.System);
		UIButton Adding = new UIButton(UIButtonType.System);
		UIButton Dividing = new UIButton(UIButtonType.System);
		UIButton Subtracting = new UIButton(UIButtonType.System);

		public ScientificCalcController() {}

		public override void ViewDidAppear(bool animated)
		{
			this.NavigationController.NavigationBar.Hidden = false; 

		}

		public override void ViewDidLoad ()
		{
			//numbers on the screen
			if (UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Pad)
			{
				number_0.SetTitle("0", UIControlState.Normal);
				number_0.SetTitle("0", UIControlState.Highlighted);
				number_0.Bounds = new CGRect(0, 0, 250, 120);
				number_0.Center = new CGPoint(200, 2000); 
				number_0.ShowsTouchWhenHighlighted = true;
				number_0.TitleLabel.Font = UIFont.SystemFontOfSize(50, UIFontWeight.Heavy);
				this.View.AddSubview(number_0);


				number_1.SetTitle("1", UIControlState.Normal);
				number_1.SetTitle("1", UIControlState.Highlighted);
				number_1.ShowsTouchWhenHighlighted = true;
				number_1.Bounds = new CGRect(0, 0, 120, 120);
				number_1.Center = new CGPoint(60, 350);
				number_1.TitleLabel.Font = UIFont.SystemFontOfSize(20, UIFontWeight.Heavy);
				this.View.AddSubview(number_1);

				number_2.SetTitle("2", UIControlState.Normal);
				number_2.SetTitle("2", UIControlState.Highlighted);
				number_2.ShowsTouchWhenHighlighted = true;
				number_2.Bounds = new CGRect(0, 0, 80, 80);
				number_2.Center = new CGPoint(240, 240);
				number_2.TitleLabel.Font = UIFont.SystemFontOfSize(20, UIFontWeight.Heavy);
				this.View.AddSubview(number_2);

				number_3.SetTitle("3", UIControlState.Normal);
				number_3.SetTitle("3", UIControlState.Highlighted);
				number_3.ShowsTouchWhenHighlighted = true;
				number_3.Bounds = new CGRect(0, 0, 80, 80);
				number_3.Center = new CGPoint(320, 240);
				number_3.TitleLabel.Font = UIFont.SystemFontOfSize(20, UIFontWeight.Heavy);
				this.View.AddSubview(number_3);

				number_4.SetTitle("4", UIControlState.Normal);
				number_4.SetTitle("4", UIControlState.Highlighted);
				number_4.ShowsTouchWhenHighlighted = true;
				number_4.Bounds = new CGRect(0, 0, 80, 80);
				number_4.Center = new CGPoint(400, 240);
				number_4.TitleLabel.Font = UIFont.SystemFontOfSize(20, UIFontWeight.Heavy);
				this.View.AddSubview(number_4);

				number_5.SetTitle("5", UIControlState.Normal);
				number_5.SetTitle("5", UIControlState.Highlighted);
				number_5.ShowsTouchWhenHighlighted = true;
				number_5.Bounds = new CGRect(0, 0, 80, 80);
				number_5.Center = new CGPoint(480, 40);
				number_5.TitleLabel.Font = UIFont.SystemFontOfSize(20, UIFontWeight.Heavy);
				this.View.AddSubview(number_5);

				number_6.SetTitle("6", UIControlState.Normal);
				number_6.SetTitle("6", UIControlState.Highlighted);
				number_5.Bounds = new CGRect(0, 0, 80, 80);
				number_5.Center = new CGPoint(560, 40);
				number_6.ShowsTouchWhenHighlighted = true;
				this.View.AddSubview(number_6);

				number_7.SetTitle("7", UIControlState.Normal);
				number_7.SetTitle("7", UIControlState.Highlighted);
				number_5.Bounds = new CGRect(0, 0, 20, 20);
				number_5.Center = new CGPoint(60, 40);
				number_7.ShowsTouchWhenHighlighted = true;
				this.View.AddSubview(number_7);

				number_8.SetTitle("8", UIControlState.Normal);
				number_8.SetTitle("8", UIControlState.Highlighted);
				number_5.Bounds = new CGRect(0, 0, 20, 20);
				number_5.Center = new CGPoint(210, 40);
				number_8.ShowsTouchWhenHighlighted = true;
				this.View.AddSubview(number_8);

				number_9.SetTitle("9", UIControlState.Normal);
				number_9.SetTitle("9", UIControlState.Highlighted);
				number_5.Bounds = new CGRect(0, 0, 20, 20);
				number_5.Center = new CGPoint(230, 40);
				number_9.ShowsTouchWhenHighlighted = true;
			this.View.AddSubview(number_9);
			}
			else if(UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Phone) {
				
			}



		}

	}
}
