// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FinanceCalculator
{
	public partial class TabMaster : UIViewController
	{

		public TabMaster(IntPtr handle) : base(handle)
		{
		}

		public TabMaster() { }

		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);


			this.NavigationController.ToolbarHidden = true;
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			this.NavigationItem.Title = "Vault";

			UITabBarController barChoices = new UITabBarController();

			ResultsControllerTotal resultControl = this.Storyboard.InstantiateViewController("ResultsControllerTotal") as ResultsControllerTotal;
			BudgetController budgetController = this.Storyboard.InstantiateViewController("BudgetController") as BudgetController;
			CameraController cameraControl = this.Storyboard.InstantiateViewController("CameraController") as CameraController;
			SettingsController settings = this.Storyboard.InstantiateViewController("SettingsController") as SettingsController;

			barChoices.SetViewControllers(new UIViewController[] {resultControl, budgetController, cameraControl, settings }, true);

			barChoices.TabBar.Hidden = false;
			barChoices.TabBar.BarStyle = UIBarStyle.Default;
			barChoices.TabBar.SelectedImageTintColor = UIColor.Red;

			barChoices.TabBar.Items[0].Title = "Vault"; ;
			barChoices.TabBar.Items[1].Title = "Manual";
			barChoices.TabBar.Items[2].Title = "Camera";
			barChoices.TabBar.Items[3].Title = "Settings";

			barChoices.ViewControllerSelected += (object sender, UITabBarSelectionEventArgs e) =>
			{
				switch (barChoices.SelectedIndex)
				{
					case 0:
						this.NavigationItem.Title = "Vault";
						this.NavigationItem.SetLeftBarButtonItem(null, true);
						this.NavigationItem.SetRightBarButtonItem(null, true);
						break;
					case 1:
						this.NavigationItem.Title = "Manual Input";
						this.NavigationItem.SetLeftBarButtonItem(null, true);
						this.NavigationItem.SetRightBarButtonItem(null, true);
						break;
					case 2:
						this.NavigationItem.Title = "Take a Photo";
						this.NavigationItem.SetRightBarButtonItem(null, true);
						this.NavigationItem.SetLeftBarButtonItem(null, true);
						break;
					default:
						this.NavigationItem.Title = "Settings";
						this.NavigationItem.SetRightBarButtonItem(null, true);
						this.NavigationItem.SetLeftBarButtonItem(null, true);
						break;
				};
			};
			this.NavigationController.AddChildViewController(barChoices);
		}
	}
}